<a href="https://colab.research.google.com/github/poornimakr2001/python/blob/ds/lab4_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Define the shape of the array
shape = (3, 4)  # Example: 3 rows and 4 columns

# Create the array filled with ones
ones_array = np.ones(shape)

# Display the array
print(ones_array)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [1]:
import numpy as np

# Example NumPy array with non-numeric values
arr = np.array([[1, 2, 3],
                [4, 5, 'a'],
                [7, 8, 9],
                ['b', 11, 12]])

# Convert the array to numeric, invalid parsing will be set to NaN
numeric_arr = np.array([np.array(row, dtype=float) if np.issubdtype(type(row[0]), np.number) else np.nan for row in arr])

# Remove rows that contain NaN (which indicates non-numeric values)
clean_arr = numeric_arr[~np.isnan(numeric_arr).any(axis=1)]

print(clean_arr)


AxisError: axis 1 is out of bounds for array of dimension 1